version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: finance-db
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: finance
    ports:
      - "4217:5432"
    volumes:
      - "C:\\java projects\\Finance\\pgdata:/var/lib/postgresql/data"
    restart: unless-stopped